### ISSUE TITLE
Betting system

### ISSUE THREAD

**Issue by RogierdeRuijter** [RogierdeRuijter/fish-race#4]
You start with an x amount of 'money'

You are able to bet money on a fish.

**Comment by RogierdeRuijter** [comment]
Every fish has a number in front of its nose. When you click on the fish the number increase by 1 and the total amount decreases by 1.

**Comment by Juicedd** [comment]
Will at first be done implicitly. There we be a prompt "Place your bets" and a count down before the race starts.
